In [1]:
# pandas 사용하기
import pandas as pd

import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# numpy 설치 -> 아나콘다 없을 때
#import numpy as np 
# 이미 불렀지롱.

---
#### 참고 링크:
 https://wikidocs.net/32829
 https://wikidocs.net/21047
<br><br><br><br><br>

## Numpy(넘파이)

Numpy는 수치 데이터를 다루는 파이썬 패키지다. Numpy의 핵심이라고 불리는 다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하는 선형 대수 계산에서 주로 사용한다. Numpy는 편의성 뿐 만 아니라, 속도면에서 순수 파이썬에 비해 압도적으로 빠르다는 장점이 있다.

**Numpy의 주요 모듈**
1. np.array() # 리스트, 튜플, 배열로 부터 ndarray를 생성
2. np.arange() # range와 비슷
3. reshape()
4. Numpy Sliceing

<br> 이 중 pandas에서 많이 쓰이는 1-4번만 설명.

5. np.asarray() # 기존의 array로 부터 ndarray를 생성
6. np.arange() # range와 비슷
7. np.linspace(start, end, num) # [start, end] 균일한 간격으로 num개 생성
8. np.logspace(start, end, num) # [start, end] log scale 간격으로 num개 생성

<br><br>

### 1. np.array 

Numpy의 핵심 ndarray. np.array()는 리스트, 튜플, 배열로 부터 ndarray를 생성합니다. 또한, 인덱스가 항상 0으로 시작한다는 특징을 갖고 있습니다.

In [12]:
a = np.array([1, 2, 3, 4, 5]) #리스트를 가지고 1차원 배열 생성
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [11]:
print(a.ndim) #차원 출력
print(a.shape) #크기 출력

1
(5,)


In [8]:
b = np.array([[10, 20, 30], [ 60, 70, 80]])  # 2차원 배열 생성. 
print(b) #출력

[[10 20 30]
 [60 70 80]]


In [10]:
print(a.ndim) #차원 출력
print(a.shape) #크기 출력

1
(5,)


In [9]:
print(b.ndim) #차원 출력
print(b.shape) #크기 출력

2
(2, 3)


차원 출력 결과
- a는 1차원 배열. 5의 배열
- b는 2차원, 2*3 행렬

---
<br><br>

### 2. np.arange() : 지정 범위에 대한 배열을 생성 

**<np.arange() 범위 지정 방법>**

- numpy.arange(start, stop, step, dtype)
- a = np.arange(n) # 0, ..., n-1까지 범위의 지정.
- a = np.arange(i, j, k) # i부터 j-1까지 k씩 증가하는 배열.

In [16]:
a = np.arange(10) #0부터 9까지
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a = np.arange(1, 10, 2) #1부터 9까지 +2씩 적용되는 범위
print(a)

[1 3 5 7 9]


---
<br><br>

### 3.  reshape()

0부터 n-1 까지의 숫자를 생성하는 arange(n) 함수에 배열을 다차원으로 변형하는 reshape()를 통해 배열을 생성

In [18]:
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


---
<br><br>

### 4.  Numpy Sliceing(슬라이싱)

ndarry를 통해 만든 다차원 배열은 파이썬 리스트처럼 Slice 기능을 지원. Slice 기능을 사용하면 원소들 중 복수 개에 접근 가능 

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
b=a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


다차원 배열 슬라이싱 -> 차원 별로 슬라이스 범위 지정

In [24]:
b=a[0, :] # 첫번째 행 출력
print(b)

[1 2 3]


In [25]:
b=a[:, 1] # 두번째 열 출력
print(b)

[2 5]


---
<br><br><br><br>

## 활용

In [27]:
data=pd.read_csv('kr_googlestore.csv')

In [28]:
data.head()

어플  \
0     Photo Editor & Candy Camera & Grid & ScrapBook   
1                                Coloring book moana   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...   
3                              Sketch - Draw & Paint   
4              Pixel Draw - Number Art Coloring Book   

                          장르   등급    리뷰 수     크기      설치 수  타입 가격  연령층  \
0               Art & Design  4.1     159  190.0     10000  무료  0  전체가   
1  Art & Design;Pretend Play  3.9     967  140.0    500000  무료  0  전체가   
2               Art & Design  4.7   87510    8.7   5000000  무료  0  전체가   
3               Art & Design  4.5  215644  250.0  50000000  무료  0  청소년   
4    Art & Design;Creativity  4.3     967    2.8    100000  무료  0  전체가   

   안드로이드 버전  업데이트_년도  업데이트_달  업데이트_년달  
0       4.0     2018       1  2018.01  
1       4.0     2018       1  2018.01  
2       4.0     2018       8  2018.08  
3       4.2     2018       6  2018.06  
4       4.4     2018       6  2018.06

In [36]:
np.mean(data.크기) #numpy로 평균 구하기

146.26777777777775

In [37]:
np.std(data.크기)  #numpy로 표준편차 구하기

147.0313472455432

In [38]:
np.var(data.크기)  #numpy로 분산 구하기

21618.217072839507

In [40]:
np.sort(data.크기)  # 전체 성분 오름차순 정렬

array([  1.1,   1.2,   2.2,   2.4,   2.5,   2.7,   2.7,   2.8,   2.9,
         3.1,   3.4,   3.6,   3.9,   4.2,   4.2,   4.2,   4.5,   4.6,
         5.2,   5.4,   5.5,   5.6,   5.6,   5.7,   6. ,   6.1,   7. ,
         7. ,   7.9,   7.9,   8. ,   8.6,   8.7,   8.9,   9.2,   9.2,
         9.4, 100. , 110. , 110. , 110. , 120. , 120. , 120. , 140. ,
       140. , 140. , 140. , 150. , 150. , 160. , 160. , 170. , 170. ,
       170. , 170. , 170. , 180. , 190. , 190. , 190. , 200. , 201. ,
       210. , 230. , 240. , 240. , 250. , 250. , 250. , 260. , 270. ,
       280. , 290. , 310. , 320. , 330. , 330. , 330. , 350. , 350. ,
       350. , 370. , 370. , 380. , 380. , 390. , 540. , 560. , 570. ,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan])

In [41]:
np.sort(data.크기)[::-1] # 전체 성분 내림차순 정렬

array([  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan, 570. , 560. , 540. , 390. , 380. , 380. , 370. , 370. ,
       350. , 350. , 350. , 330. , 330. , 330. , 320. , 310. , 290. ,
       280. , 270. , 260. , 250. , 250. , 250. , 240. , 240. , 230. ,
       210. , 201. , 200. , 190. , 190. , 190. , 180. , 170. , 170. ,
       170. , 170. , 170. , 160. , 160. , 150. , 150. , 140. , 140. ,
       140. , 140. , 120. , 120. , 120. , 110. , 110. , 110. , 100. ,
         9.4,   9.2,   9.2,   8.9,   8.7,   8.6,   8. ,   7.9,   7.9,
         7. ,   7. ,   6.1,   6. ,   5.7,   5.6,   5.6,   5.5,   5.4,
         5.2,   4.6,   4.5,   4.2,   4.2,   4.2,   3.9,   3.6,   3.4,
         3.1,   2.9,   2.8,   2.7,   2.7,   2.5,   2.4,   2.2,   1.2,
         1.1])